export const navBarDiv: string;
export const addressTime: string;
export const fullAddress: string;
export const inputArea: string;
export const searchIcon: string;
export const buttons: string;
export const loginButton: string;
export const cartButton: string;
export const cartButtonDiv: string;
